font:
    size: 20.0
    # builtin_box_drawing: false
    normal:
        family: Inconsolata Nerd Font Mono
        # family: Iosevka
        style: Regular

    bold:
        style: Bold

    italic:
        style: Regular Oblique
        # style: Italic

    bold_italic:
        style: Bold Oblique
        # style: Bold Italic

    offset:
        x: 0
        y: 3

    # glyph_offset:
    #     x: 0
    #     y: 0

window:
    dimensions:
        # This doesn't actually matter, since chunkwm handles it, but set it anyway
        columns: 120
        lines: 40
    padding:
        x: 10
        y: 10
    dynamic_padding: true
    decorations: none
    opacity: 1
    option_as_alt: Both

cursor:
    style:
        blinking: Always
    blink_interval: 600

colors:
    # Copied from iTerm2's Tango Dark scheme
    primary:
        background: '#000000'
        foreground: '#dbded8'
    normal:
        black:      '#000000'
        red:        '#d71e00'
        green:      '#5da602'
        yellow:     '#cfad00'
        blue:       '#417ab3'
        magenta:    '#88658d'
        cyan:       '#00a7aa'
        white:      '#dbded8'
    bright:
        black:      '#676965'
        red:        '#f44135'
        green:      '#98e342'
        yellow:     '#fcea60'
        blue:       '#83afd8'
        magenta:    '#bc93b6'
        cyan:       '#37e5e7'
        white:      '#f1f1ef'
    cursor:
        text:       CellBackground
        cursor:     CellForeground
    draw_bold_text_with_bright_colors: true

hints:
    enabled:
      - regex: "((magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:|go/|g/|b/|cl/|cs/|t/|shortn/|slides/|docs/|yaqs/|google3/|mail/|scripts2/|gpaste/|meme/|omg/|dashboards/)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`¬]+|[a-zA-Z]+@)"
        command: /Users/jls83/open_all_links.sh
        post_processing: true
        mouse:
            enabled: true
            mods: Control
        binding:
            key: U
            mods: Control|Shift
