font:
    size: 18.0
    normal:
        family: Inconsolata Nerd Font Mono
        style: Regular

    bold:
        family: Inconsolata Nerd Font Mono
        style: Bold

    italic:
        family: Inconsolata Oblique
        style: Oblique

    # bold_italic:
    #     family: Menlo
    #     style: Bold-Italic

    offset:
        x: 0
        y: 2

window:
    dimensions:
        # This doesn't actually matter, since chunkwm handles it, but set it anyway
        columns: 120
        lines: 40
    padding:
        x: 10
        y: 10
    decorations: none
    opacity: 0.9

cursor:
    style:
        blinking: Always
    blink_interval: 600

draw_bold_text_with_bright_colors: true
colors:
    # Copied from iTerm2's Tango Dark scheme
    primary:
        background: '#000000'
        foreground: '#dbded8'
    normal:
        black:      '#000000'
        red:        '#d71e00'
        green:      '#5da602'
        yellow:     '#cfad00'
        blue:       '#417ab3'
        magenta:    '#88658d'
        cyan:       '#00a7aa'
        white:      '#dbded8'
    bright:
        black:      '#676965'
        red:        '#f44135'
        green:      '#98e342'
        yellow:     '#fcea60'
        blue:       '#83afd8'
        magenta:    '#bc93b6'
        cyan:       '#37e5e7'
        white:      '#f1f1ef'
    cursor:
        text:       CellBackground
        cursor:     CellForeground

hints:
    enabled:
      - regex: "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`¬]+"
        command: open
        post_processing: true
        mouse:
            enabled: true
            mods: Control
      # Open Google-specific URLs with ctrl+click
      - regex: "(go/|g/|b/|cl/|cs/|t/|shortn/|slides/|docs/|yaqs/|google3/|mail/|scripts2/|gpaste/)[^\u0001-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`¬]+"
        command: /Users/josephsanders/open_go_links.sh
        post_processing: true
        mouse:
            enabled: true
            mods: Control
      # Open `who/` entries for the target user
      - regex: "[a-zA-Z]+@"
        command: /Users/josephsanders/open_who_links.sh
        post_processing: true
        mouse:
            enabled: true
            mods: Control
