font:
    size: 18.0
    normal:
        family: Inconsolata
        style: Regular

    bold:
        family: Inconsolata
        style: Bold

    italic:
        family: Inconsolata
        style: Italic

    offset:
        x: 0
        y: 2

window:
    dimensions:
        # This doesn't actually matter, since chunkwm handles it, but set it anyway
        columns: 120
        lines: 40
    padding:
        x: 10
        y: 10
    decorations: none

background_opacity: 0.9

mouse:
    url:
        modifiers: control
