#!/bin/bash

#
# NOTE: any 'chunkc' command that is run from this config file
#       that is NOT 'chunkc core::<..>' or 'chunkc set ..'
#       MUST be put in the background using &
#
#       e.g:
#       chunkc tiling::rule --owner Finder --name Copy --state float &
#

# Logging options
# NOTE: specify the absolutepath of the file to use for logging.
#       'stdout' or 'stderr' can be used instead of an actual filepath.
chunkc core::log_file stdout
chunkc core::log_level warn

# Plugin options; NOTE: `plugin_dir` must be absolute path
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins
chunkc core::hotload 0

# chunkwm-tiling settings
chunkc set custom_bar_enabled            0
chunkc set custom_bar_all_monitors       0
chunkc set custom_bar_offset_top         22
chunkc set custom_bar_offset_bottom      0
chunkc set custom_bar_offset_left        0
chunkc set custom_bar_offset_right       0

DESKTOP_OFFSET=15

chunkc set global_desktop_mode           bsp
chunkc set global_desktop_offset_top     $DESKTOP_OFFSET
chunkc set global_desktop_offset_bottom  $DESKTOP_OFFSET
chunkc set global_desktop_offset_left    $DESKTOP_OFFSET
chunkc set global_desktop_offset_right   $DESKTOP_OFFSET
chunkc set global_desktop_offset_gap     $DESKTOP_OFFSET

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

# BSP settings
chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           intrinsic
chunkc set window_float_next             0
chunkc set window_region_locked          1

chunkc set mouse_move_window             \"fn 1\"
chunkc set mouse_resize_window           \"fn 2\"
chunkc set mouse_motion_interval         35

chunkc set preselect_border_color        0xffd75f5f
chunkc set preselect_border_width        5
chunkc set preselect_border_radius       7
chunkc set preselect_border_outline      1

# chunkwm-border settings
chunkc set focused_border_color          0xff0f6288
chunkc set focused_border_width          5
chunkc set focused_border_radius         7
# 1 = "inline" border; 0 = "outline" border
chunkc set focused_border_outline        1
chunkc set focused_border_skip_floating  0
chunkc set focused_border_skip_monocle   0

# chunkwm-ffm settings
chunkc set ffm_bypass_modifier           fn
chunkc set ffm_standby_on_float          1

# Plugins to load when starting
chunkc core::load border.so
chunkc core::load tiling.so
chunkc core::load ffm.so

# Explicit tiling rules
chunkc tiling::rule --owner Finder --name Copy --state float &
chunkc tiling::rule --owner \"App Store\" --state float &
chunkc tiling::rule --owner Emacs --except "^$" --state tile &

# TODO: Add tiling rules for PyCharm pop-up windows (except test runner!)

