ARROW=$'>>'
PROMPT=$'
%F{208}%D{%H:%M:%S}%f %~ $(virtualenv_prompt_info) $(git_prompt_info) \
%F{221}${ARROW}%f '

ZSH_THEME_GIT_PROMPT_PREFIX="%F{5}:: "
ZSH_THEME_GIT_PROMPT_SUFFIX="%f"
ZSH_THEME_GIT_PROMPT_DIRTY=" %F{9}✘%F{5}"
ZSH_THEME_GIT_PROMPT_CLEAN=" %F{2}✔%F{5}"

ZSH_THEME_VIRTUALENV_PREFIX="$FG[102]("
ZSH_THEME_VIRTUALENV_SUFFIX=")%{$reset_color%}"
