# vim: ft=ruby:

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

# For yabai, skhd
tap "koekeishiya/formulae"

brew "bat"
brew "fd"
brew "fzf"
brew "git-delta"
brew "neovim"
brew "pipx"
brew "ripgrep"
brew "stow"
brew "tmux"

# Explicit bzip and zlib steps are to work around a pyenv bug
brew "pyenv"
brew "bzip2"
brew "zlib"

brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"

cask "alacritty"
